### ISSUE TITLE
cannot insert coindexation variable in graphical tree

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#103]
E.g. for a Nom, clicking on Nom.x has no effect

**Comment by nschneid** [comment]
I had forgotten to include a gap in the sentence:

`the Secretary may waive , in whole or in part , the requirements for repayment of scholarship amounts on the basis of economic conditions which _. may affect the ability of scholarship recipients to find work as realtime writers .`

After adding the gap and reparsing it assigns coindexation variables and they can be toggled in the graphical interface. Very strange.

**Comment by bwaldon** [comment]
This is due to some over-zealous automated label correction in `activedoptree.py`: https://github.com/nschneid/activedop/blob/master/activedoptree.py#L194-L200C52

https://github.com/nschneid/activedop/pull/106 deletes the offending code should we want to get rid of this

**Comment by nschneid** [comment]
OK yeah I think that's a matter for the CGEL validator not activedop itself
