### ISSUE TITLE
Dragging category from label list to trash causes error

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#13]
The node-deletion code needs a way to tell current tree nodes apart from labels in the list

**Comment by bwaldon** [comment]
As of https://github.com/nschneid/activedop/pull/101, this error is handled without causing a server crash: 

<img width="788" alt="Screenshot 2024-11-18 at 12 54 40 PM" src="https://github.com/user-attachments/assets/6cf80f99-9b12-4c6a-8b19-0c860bb96d2e">

... though the message is a bit obscure.

**Comment by nschneid** [comment]
Good enough for me
