### ISSUE TITLE
[Brandon's master branch] right-click nonterminal to enumerate subtree options gives an error

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#22]
"ERROR: cannot parse tree bracketing not enough values to unpack (expected 2, got 1)"

**Comment by bwaldon** [comment]
Will investigate today. (I haven't used the 'enumerate subtree' functionality in my own testing).

**Comment by nschneid** [comment]
No rush, I'm just poking at it to see what breaks

**Comment by bwaldon** [comment]
Addressed by https://github.com/bwaldon/activedop/commit/d90b22ce96a4e11b6a8cde0590246359d41c24a9

**Comment by nschneid** [comment]
WFM. Will close when merged into the main repo

**Comment by bwaldon** [comment]
I believe this is no longer an active issue and can be closed
