### ISSUE TITLE
apostrophe appears on wrong token in tree

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#28]
<img width="620" alt="image" src="https://github.com/user-attachments/assets/94b3a721-5fe0-4be3-839b-193f7813433f">

**Comment by bwaldon** [comment]
Addressed by https://github.com/bwaldon/activedop/commit/9f5233e72380b9cc257069c0a7e4771279a01e12

**Comment by bwaldon** [comment]
This behavior was due to handle_punctuation() (in the old punctuation handling regime), which would have stripped `'` from `'re` and added it as a `:p` property of the preceding terminal, causing downstream editing issues when `:p` tags were subsequently merged with `:t` tags.

**Comment by bwaldon** [comment]
(We don't see this behavior after https://github.com/nschneid/activedop/commit/c349d9b2aef192b28d519d6e5f3f90ae69304e36, so I think we can close this issue).
