### ISSUE TITLE
[Brandon's master branch] navigating to certain sentences gives error

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#29]
```

    File "/Users/nathan/dev/nlp-tools/activedop-brandon/app.py", line 704, in edit

    treestr=treestr, senttok=' '.join(senttok), id=id,
        ^^^^^^^^^^^^^^^^^

    TypeError: sequence item 6: expected str instance, NoneType found
```

**Comment by nschneid** [comment]
(this is new since I did a git pull just now)

**Comment by nschneid** [comment]
We think it may be specific to sentences with added gaps.

**Comment by bwaldon** [comment]
I believe this should be addressed by: https://github.com/bwaldon/activedop/commit/6f2cc70600b118a6088b657b654cc12bfc411848

**Comment by bwaldon** [comment]
Marking as closed because this is addressed on Nathan's branch
