### ISSUE TITLE
Re-write features that depend on old tag handling method

### ISSUE THREAD

**Issue by bwaldon** [nschneid/activedop#43]
Several changes implemented on my fork (e.g., https://github.com/bwaldon/activedop/commit/e20926e65dd530d6f32b4de0aa9871c12435f864, https://github.com/bwaldon/activedop/commit/7c40f32bc69a4c53579af6154f95652edd451160, https://github.com/bwaldon/activedop/commit/9f5233e72380b9cc257069c0a7e4771279a01e12, https://github.com/bwaldon/activedop/commit/ec87142bd4793bb592b3e100c6535eab376cb82e, https://github.com/bwaldon/activedop/commit/dc153497925d863f05eade9f1d7bd35f2caacb2d, https://github.com/bwaldon/activedop/commit/564eb12a21572c41e8ec574bb9bfee917b877ce6) depend on my old solution for tag handling, which we amended at https://github.com/nschneid/activedop/commit/5ef2fd2c8c195674b7d5af3df398d3a43a208f6c. I'm not sure about the best way to proceed from here; merging in these commits (either via conventional `merge` or via `rebase`) would require substantial merge conflict resolution. 

Punctuation handling exemplifies the issue: before rendering trees as graphical, user-manipulable objects in activedop edit mode, we merge a node's `:t` string with its `postpunct` and `prepunct` strings and clear the `postpunct` and `prepunct` tags of terminal nodes. (Otherwise, when converting from CGEL format to export/discbracket formats, punctuation would be treated as distinct nodes on the graphical representation of the tree). But we need to somehow preserve the postpunct / prepunct information associated with terminal nodes of the CGEL tree so that those tags appear in the text edit window after any graphical manipulations performed by the user. The old solution was to store a dictionary of features (including not just prepunct/postpunct but also xpos, lemma, etc) and pass those to the 'stripped' CGEL tree after user manipulations on the graphical tree. It's possible we'll want a 'hybrid' solution: prepunct and postpunct info is saved in a dictionary, but other node data is not (per the new tag handling method).

**Comment by nschneid** [comment]
> (Otherwise, when converting from CGEL format to export/discbracket formats, punctuation would be treated as distinct nodes on the graphical representation of the tree).

There was supposed to be an option in cgel.py that would control whether the PTB-style bracketed format would include punctuation. I see I forgot to update the `Tree.ptb()` function signature so I will do that.

**Comment by nschneid** [comment]
nert-nlp/cgel@87cb33a

This should make it no longer necessary to clear out and separately cache `prepunct` and `postpunct`, right?

**Comment by nschneid** [comment]
#44 regarding the various things that need to be considered for punctuation.

**Comment by bwaldon** [comment]
Awesome, I think this is going to massively simplify `app.py` at multiple places. 

I've experimented with the `punct` option for the `ptb()` tree method, and I get similar output regardless of how I set that option: For example:

```
> cgel_tree = '(Clause\n    :Subj (NP\n        :Det (DP\n            :Head (D :t "The"))\n        :Head (Nom\n            :Head (N :t "girl")))\n    :Head (VP\n        :Head (V :t "ate")\n        :Obj (NP\n            :Head (Nom\n                :Head (N :t "pizza")\n                :Mod (PP\n                    :Head (P :t "with")\n                    :Obj (NP\n                        :Head (Nom\n                            :Head (N :t "tomatoes" :p "."))))))))\n'
> cgel.parse(cgel_tree)[0].ptb(punct=True)
'(Clause (NP-Subj (DP-Det (D-Head The)) (Nom-Head (N-Head girl))) (VP-Head (V-Head ate) (NP-Obj (Nom-Head (N-Head pizza) (PP-Mod (P-Head with) (NP-Obj (Nom-Head (N-Head tomatoes) (. .))))))))'
> cgel.parse(cgel_tree)[0].ptb(punct=False)
'(Clause (NP-Subj (DP-Det (D-Head The)) (Nom-Head (N-Head girl))) (VP-Head (V-Head ate) (NP-Obj (Nom-Head (N-Head pizza) (PP-Mod (P-Head with) (NP-Obj (Nom-Head (N-Head tomatoes) (. .))))))))'
```

**Comment by bwaldon** [comment]
[Desired output: final node is `(N-Head tomatoes.)`]

**Comment by nschneid** [comment]
Must be a bug in cgel.py. Not at my computer rn. Maybe you could track it
down? It should be checking punct before it adds the punctuation node.

**Comment by bwaldon** [comment]
https://github.com/nert-nlp/cgel/pull/121
