### ISSUE TITLE
Export in CGEL format

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#6]

**Comment by nschneid** [comment]
88f4a5c implements at least part of this. Not sure if I meant there should be a way to export all the trees at once.

**Comment by bwaldon** [comment]
https://github.com/bwaldon/activedop/commit/bad407feb1f21d227880458d1781981771b7fd67 implements 'export all trees in cgel format'

**Comment by nschneid** [comment]
With #21 the .cgel format is used in the textarea editor, so there is no need for a separate export functionality.
