### ISSUE TITLE
error loading the annotate page

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#60]
<img width="636" alt="image" src="https://github.com/user-attachments/assets/0b21b917-ed6a-4ca5-94bf-967e0d7c0106">

This is with:

```py
GRAMMAR = 'cgelbank2-punct/'
SENTENCES = 'newsentsExample.csv'
```

And the latest cgel.py.

**Comment by bwaldon** [comment]
I can reproduce this. There's a stage in the call to `tree_process` where the first sentence is parsed such that it includes a nonterminal `HYPH`: 

<img width="688" alt="Screenshot 2024-09-05 at 9 54 13 AM" src="https://github.com/user-attachments/assets/af318674-89a6-4d3e-bfc3-148d4f26f403">

I suspect this is an escaping problem and will investigate further.
