### ISSUE TITLE
Non-tree context

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#7]
Way to show parts of the sentence that aren't properly terminals in the tree, e.g. punctuation

**Comment by nschneid** [comment]
Can punctuation be appended to the terminals in the tree visualization, without being parsed by discodop as part of the terminals?

**Comment by nschneid** [comment]
It probably makes sense to just include punctuation in the annotation trees. With https://github.com/nert-nlp/cgel/commit/a19790560327bdf1af2f4869896b50d16e0bd44b, cgel2ptb.py will include punctuation nodes in the PTB-style bracketing. May need tweaking—I haven't tested retraining discodop with this.

**Comment by bwaldon** [comment]
I think this is ready to close, following https://github.com/nschneid/activedop/commit/c349d9b2aef192b28d519d6e5f3f90ae69304e36
