### ISSUE TITLE
Error when entering annotate mode when punctuation not separately tokenized from adjacent tokens

### ISSUE THREAD

**Issue by bwaldon** [nschneid/activedop#76]
@mebwells was testing the new version and encountered the following error: 

`ValueError: Indices must occur at most once` 

This error is raised when punctuation isn't tokenized separately from adjacent tokens, as in:

`Not later than 270 days after the commencement of the study required by paragraph (1), the Secretary of Commerce shall, in consultation with the Secretary of Energy and the Director of the Office of Science and Technology Policy, submit to Congress a report on such study.`

It goes away with proper tokenization:

`Not later than 270 days after the commencement of the study required by paragraph ( 1 ) , the Secretary of Commerce shall , in consultation with the Secretary of Energy and the Director of the Office of Science and Technology Policy , submit to Congress a report on such study .`

**Comment by bwaldon** [comment]
Problem appears to be restricted to cases where a token includes a number surrounded by parentheses, e.g., `(1)`. My hunch: the number is being mis-analyzed as a ptree terminal index.

**Comment by nschneid** [comment]
Are parentheses escaped if they are not tokenized off?

**Comment by bwaldon** [comment]
Currently, no -- we only escape them if they're tokenized off. But I think escaping regardless of tokenization would solve the issue!

**Comment by nschneid** [comment]
Also worth testing emoticons like `:-)`

**Comment by nschneid** [comment]
A hacky solution would be to substitute lookalike characters e.g. U+FE59 and U+FE5A
https://www.compart.com/en/unicode/search?q=parenthesis#characters
