### ISSUE TITLE
gap variables and too-long sentence

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#87]
tokens: `I have said above , that the atonement is to be regarded as that by which God has bridged over the gulf which _. separated between what sin had made us , _. and what it was the desire of the divine love that we should become . _. _.`

<img width="408" alt="image" src="https://github.com/user-attachments/assets/37663058-a57e-4665-90c0-7194e76e4d6c">

I had graphically edited the last gap to be GAP.z, but when I changed the second-to-last gap to GAP.b, the last one reverted to GAP.x.

I cannot edit in the textbox because the tree is too large ([bigtree.txt](https://github.com/user-attachments/files/17321041/bigtree.txt)):

<img width="408" alt="image" src="https://github.com/user-attachments/assets/7db36705-3949-4e3b-8c94-423d6fccead7">

I wonder if a solution is to submit the form via POST rather than GET.

**Comment by nschneid** [comment]
(and note to self: 'become' should have a PredComp not Obj)

**Comment by bwaldon** [comment]
It looks like graphical edits to gap POS tags aren't being reflected in the text box. (E.g., when I change the POS tag for the last gap from `GAP.x` to `GAP.z`, the tree string still has `:Mod (x / GAP)` as its last terminal).

**Comment by nschneid** [comment]
> I wonder if a solution is to submit the form via POST rather than GET.

https://stackoverflow.com/questions/22028398/flask-error-414-request-uri-too-large

**Comment by bwaldon** [comment]
I think this is ready to close
