### ISSUE TITLE
On server restart, tokenized sentence string is reloaded from sentences list even if an annotation is saved

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#9]
Changing tokenization means there is no way to look up the saved annotation without manually retokenizing. This is because annotations appear to be indexed by the sentence string, not by a sentence ID.

In the meantime, the solution is to manually keep the sentences list in sync with any changes to the tokenization (and rerun initpriorities after any change).

**Comment by bwaldon** [comment]
Addressed by https://github.com/bwaldon/activedop/commit/88180dcdfa6964913b4bb910304c97ac604651d3

Instead of passing a list of sentences to `settings.cfg` (e.g., `newsentsExample.txt`), pass a csv with an `id` column and a `sentence` column (see `newsentsExample.csv`)
