### ISSUE TITLE
subscripts being discarded from POS categories

### ISSUE THREAD

**Issue by nschneid** [nschneid/activedop#90]
Should have `N_pro` and `V_aux`:

<img width="485" alt="image" src="https://github.com/user-attachments/assets/cc805050-c5de-4bb7-8a49-b51691defb2c">

**Comment by nschneid** [comment]
I've noticed that the gtree does provide labels with underscores as an option. Previously we had removed them in the non-CGEL formats, presumably because disco-dop did not like underscores within categories.

**Comment by nschneid** [comment]
Auto parse now showing `Npro`, `Vaux`! There is one small thing: if I change the CGEL format annotation to `Npro` it still validates (should properly be `N_pro`).

**Comment by bwaldon** [comment]
Ah I think I see what's causing that -- the `cgel_tree` attribute of the `ActivedopTree` object has the right label (it's corrected to `N_pro` on `__init__`) but the text box window won't update until the user performs a graphical operation.

**Comment by nschneid** [comment]
Ideally the underscore insertion will happen only for dop-parser output.

**Comment by bwaldon** [comment]
As in: if the user changes the annotation to `Npro` in the text window, we shouldn't automatically insert the `_`? (And instead, the user should get a validation message about an illicit category?)

**Comment by nschneid** [comment]
That's what I was thinking yeah...technically `Npro` is not a valid category in CGEL markup.

**Comment by bwaldon** [comment]
Okay, I think I have a solution that gets us closer to what we want: 

https://github.com/bwaldon/activedop/commit/28d89de84d14346c5ab419a2690ef990ef1ee8b7 introduces an option `correct_cgel_labels` in initialization of an ActivedopTree class object. When `True`, we re-insert underscores in category labels of the CGELTree object (and re-insert hyphens in function labels). This param is set to `False` when the user makes edits from the text window. It's set to `True` when passing a dopparser-produced tree to the edit window. 

One limitation: this param is also set to `True` when users make a graphical edit. This means, for example: if a user could manually label a terminal as `Vaux` in the text window, the label will be automatically corrected to `V_aux` upon a subsequent graphical edit.

Depends on updating the cgel submodule: https://github.com/bwaldon/cgel/commit/0ee2d7ad98d5bdda7022e6a8327deeeeed8a5468 (`correct_cgel_labels` also needs to be a parameter of `load()` in cgel/scripts/activedopexport2cgel.py). 

We'll also need to update the validator in cgel.py -- category names are currently validated with regex matching (see https://github.com/nert-nlp/cgel/blob/751c6e6f7e9998f9f966ed441dc8828657b67ca6/cgel.py#L743-L749). I think we probably need to evaluate a tree's category labels against a fixed set if we want to distinguish between, e.g., `Npro` and `N_pro` in validation.

**Comment by bwaldon** [comment]
Ok — should I open PRs on this repo and the CGELBank repo with the above
changes?

**Comment by nschneid** [comment]
Will the validator now flag the error if the underscore is removed? If so I think that should suffice right?

**Comment by bwaldon** [comment]
No because we convert from ptree to get the CGEL tree string that the user
sees in the edit window text box. The ptree labels don’t contain
underscores. Unless there’s some stage at which underscores are inserted in
labels such as Npro, Vaux, etc, the user will get a ton of CGEL validator
errors in the edit window.

**Comment by bwaldon** [comment]
Following convo 11/12: adding keyword argument to ActiveDopTree constructor should address this. (When construction is from CGEL tree, don't do CGELTree -> ptree -> CGELTree conversion; just CGELTree -> ptree).
